const $=id=>document.getElementById(id);
let hist=JSON.parse(localStorage.getItem('nexora_history')||'[]');
let interactionId=localStorage.getItem('nexora_interaction_id')||'';

function openPanel(name){
 document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===name));
 document.querySelectorAll('.side-item[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));
 const titles={chat:['NEXORA','Advanced Neural Intelligence'],code:['CODING LAB','Development workspace'],search:['WEB SEARCH','Global research'],image:['IMAGE FORGE','Creative engine'],video:['VIDEO LAB','Media engine'],assistant:['AI ASSISTANT','Personal intelligence']};
 if(titles[name]){$('panelTitle').textContent=titles[name][0];$('panelSubtitle').textContent=titles[name][1]}
 const composer=$('composerWrap'); if(composer) composer.style.display=name==='chat'?'block':'none';
 const ws=$('workspace'); if(ws) ws.scrollIntoView({behavior:'smooth',block:'start'});
 closeMenus();
}
function closeMenus(){const nav=$('mainNav');if(nav)nav.classList.remove('open');const sb=$('chatSidebar');if(sb)sb.classList.remove('open')}
$('menuBtn')?.addEventListener('click',()=> $('mainNav').classList.toggle('open'));
$('sideBtn')?.addEventListener('click',()=> $('chatSidebar').classList.toggle('open'));
document.querySelectorAll('.side-item[data-panel]').forEach(b=>b.addEventListener('click',()=>openPanel(b.dataset.panel)));
$('themeBtn')?.addEventListener('click',()=>document.body.classList.toggle('light-hint'));

function addMessage(role,text){
 const d=document.createElement('div');d.className='msg '+role;
 const a=document.createElement('div');a.className='avatar';a.textContent=role==='assistant'?'N':'Y';
 const c=document.createElement('div');c.className='content';
 const n=document.createElement('div');n.className='name';n.textContent=role==='assistant'?'NEXORA':'YOU';
 const t=document.createElement('div');t.textContent=text;c.append(n,t);d.append(a,c);$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight;return t;
}
function renderHistory(){const m=$('messages');m.innerHTML='';if(!hist.length){return}hist.slice(-30).forEach(x=>addMessage(x.role==='user'?'user':'assistant',x.text||''))}
async function sendMessage(){
 const input=$('chatInput'),text=input.value.trim();if(!text)return;input.value='';input.style.height='auto';
 addMessage('user',text);hist.push({role:'user',text});localStorage.setItem('nexora_history',JSON.stringify(hist.slice(-50)));
 const target=addMessage('assistant','NEXORA is thinking…');
 try{const payload={message:text,model:'gemini-3.6-flash'};if(interactionId)payload.interaction_id=interactionId;
  const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch(_){ }if(!r.ok)throw new Error(d.detail||'AI request failed');
  interactionId=d.interaction_id||interactionId;if(interactionId)localStorage.setItem('nexora_interaction_id',interactionId);target.textContent=d.reply||'No response received.';hist.push({role:'assistant',text:d.reply||''});localStorage.setItem('nexora_history',JSON.stringify(hist.slice(-50)));
 }catch(e){target.textContent='Connection error: '+e.message}
}
$('chatInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage()}});
$('chatInput')?.addEventListener('input',e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,130)+'px'});
function newChat(){hist=[];interactionId='';localStorage.removeItem('nexora_history');localStorage.removeItem('nexora_interaction_id');$('messages').innerHTML='';openPanel('chat')}
function quick(t){openPanel('chat');$('chatInput').value=t;sendMessage()}
function toggleSettings(){alert('NEXORA settings: theme, voice input and workspace controls are available from the interface.')}
async function searchWeb(){const q=$('searchInput').value.trim();if(!q)return;$('results').innerHTML='<p class="loading">Searching the web…</p>';try{const r=await fetch('/api/search?q='+encodeURIComponent(q));const d=await r.json();if(!r.ok)throw new Error(d.detail||'Search failed');$('results').innerHTML=(d.results||[]).map(x=>`<div class="result"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.title||x.url)}</a><p>${esc(x.snippet||'')}</p></div>`).join('')||'<p>No results found.</p>'}catch(e){$('results').textContent=e.message}}
function generateImage(){const p=$('imagePrompt').value.trim();if(!p)return;$('imageResult').innerHTML='<p class="loading">Generating image…</p><div class="media"><img src="/api/image?prompt='+encodeURIComponent(p)+'" alt="Generated by NEXORA" onload="this.parentElement.previousElementSibling?.remove()" onerror="this.parentElement.previousElementSibling?.remove();this.parentElement.insertAdjacentHTML(\'afterbegin\',\'<p>Image generation failed.</p>\')"></div>'}
async function generateVideo(){const p=$('videoPrompt').value.trim();if(!p)return;$('videoResult').textContent='Submitting video job…';try{const r=await fetch('/api/video',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p})});const d=await r.json();$('videoResult').textContent=d.message||'Video gateway response received.'}catch(e){$('videoResult').textContent='Video provider is not configured yet.'}}
function runCode(){$('preview').srcdoc=$('codeInput').value}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function startVoice(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Voice input is not supported by this browser.');return}const r=new R();r.lang='en-US';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>{$('chatInput').value=e.results[0][0].transcript;sendMessage()};r.start()}
renderHistory();runCode();
