let hist=JSON.parse(localStorage.getItem('nexora_history')||'[]');const $=id=>document.getElementById(id);
function openPanel(n){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$(n).classList.add('active');document.querySelectorAll('.workspace aside button').forEach(x=>x.classList.toggle('active',x.dataset.p===n));document.querySelector('.workspace').scrollIntoView({behavior:'smooth'})}
document.querySelectorAll('.workspace aside button').forEach(b=>b.onclick=()=>openPanel(b.dataset.p));
function add(role,text){let d=document.createElement('div');d.className='msg';d.innerHTML='<b>'+(role==='ai'?'N':'Y')+'</b><span><strong>'+(role==='ai'?'NEXORA':'YOU')+'</strong><br></span>';d.querySelector('span').append(document.createTextNode(text));$('messages').appendChild(d);$('messages').scrollTop=$('messages').scrollHeight}
async function sendMessage(){let i=$('chatInput'),t=i.value.trim();if(!t)return;i.value='';add('user',t);hist.push({role:'user',text:t});localStorage.setItem('nexora_history',JSON.stringify(hist.slice(-50)));add('ai','NEXORA is processing...');let last=$('messages').lastElementChild.querySelector('span');try{let r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:t,history:hist.slice(0,-1),model:'gemini-2.5-flash'})});let d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');last.innerHTML='<strong>NEXORA</strong><br>'+esc(d.reply||'No response');hist.push({role:'assistant',text:d.reply||''});localStorage.setItem('nexora_history',JSON.stringify(hist.slice(-50)))}catch(e){last.innerHTML='<strong>NEXORA</strong><br>'+esc('Connection error: '+e.message)}}
$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendMessage()}});
async function searchWeb(){let q=$('searchInput').value.trim();if(!q)return;$('results').innerHTML='<p>Searching...</p>';try{let r=await fetch('/api/search?q='+encodeURIComponent(q)),d=await r.json();$('results').innerHTML=(d.results||[]).map(x=>'<div class="result"><a target="_blank" href="'+x.url+'">'+esc(x.title||x.url)+'</a><p>'+esc(x.snippet||'')+'</p></div>').join('')||'<p>No results.</p>'}catch(e){$('results').textContent=e.message}}
function generateImage(){let p=$('imagePrompt').value.trim();if(!p)return;$('imageResult').innerHTML='<p>Generating...</p><img src="/api/image?prompt='+encodeURIComponent(p)+'" onload="this.previousElementSibling.remove()" alt="NEXORA AI image">'}
async function generateVideo(){let p=$('videoPrompt').value.trim();if(!p)return;$('videoResult').textContent='Submitting video job...';try{let r=await fetch('/api/video',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:p})}),d=await r.json();$('videoResult').textContent=d.message||'Video gateway response received.'}catch(e){$('videoResult').textContent='Video provider is not configured yet.'}}
function runCode(){$('preview').srcdoc=$('codeInput').value}function quick(t){openPanel('chat');$('chatInput').value=t;sendMessage()}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function startVoice(){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Voice input is not supported by this browser.');return}let r=new R();r.lang='en-US';r.onresult=e=>{$('chatInput').value=e.results[0][0].transcript;sendMessage()};r.start()}runCode();
